// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Prisma 7 dropped schema-level `directUrl`; if the pooled DATABASE_URL
    // (e.g. Neon/Vercel Postgres pgbouncer) causes migrate issues in
    // production, point DATABASE_URL itself at the *direct* connection
    // string for migrate/deploy runs, or set shadowDatabaseUrl here.
    shadowDatabaseUrl: process.env["DIRECT_URL"] || undefined,
  },
});
